### ISSUE TITLE
Error when running with no input arguments

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/cromwell-tools#97]
When I try to run cromwell-tools without specifying a command I get the following error:

```
🐋  ~ 1.8 cromwell-tools
Traceback (most recent call last):
  File "/usr/local/bin/cromwell-tools", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/cromwell_tools/cli.py", line 258, in main
    command, args = parser(arguments)
  File "/usr/local/lib/python3.7/site-packages/cromwell_tools/cli.py", line 250, in parser
    command = getattr(CromwellAPI, args['command'])
TypeError: getattr(): attribute name must be string
```

I would expect you'd get usage info instead of a crash.

**Comment by lbergelson** [comment]
Version is cromwell-tools 2.3.0.  It looks like this might actually be fixed though in master...

**Comment by rexwangcc** [comment]
@lbergelson Thanks for filing the issue! I have confirmed it's a bug on both `v2.3.0` and `master`... Will fix it ASAP :)
